let
    Source = Csv.Document(File.Contents(pCsvPath), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    H = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    C = Table.TransformColumnNames(H, each Text.Trim(_)),
    I = Table.AddIndexColumn(C, "SortOrder", 1, 1, Int64.Type),
    T = Table.TransformColumnTypes(I,{{"ID", Int64.Type},{"Work Item Type", type text},{"Title 1", type text},{"Title 2", type text},{"Title 3", type text},{"Assigned To", type text},{"State", type text},{"Tags", type text}}),
    A1 = Table.AddColumn(T,"WorkItemId", each [ID]),
    A2 = Table.AddColumn(A1,"WorkItemType", each Text.Proper(Text.Trim(Text.From([Work Item Type])))),
    A3 = Table.AddColumn(A2,"FeatureTitle", each [Title 1]),
    A4 = Table.AddColumn(A3,"UserStoryTitle", each [Title 2]),
    A5 = Table.AddColumn(A4,"TaskTitle", each [Title 3]),
    A6 = Table.AddColumn(A5,"DisplayTitle", each if [WorkItemType]="Feature" then [Title 1] else if [WorkItemType]="User Story" then [Title 2] else [Title 3]),
    A7 = Table.AddColumn(A6,"TrackRec", each FunctionsAzureDevOps[FnTrackFromText]([Title 1])),
    E1 = Table.ExpandRecordColumn(A7,"TrackRec",{"TrackCode","TrackName"},{"TrackCode","TrackName"}),
    E2 = Table.AddColumn(E1,"AssignedRec", each FunctionsAzureDevOps[FnParseAssignedTo]([Assigned To])),
    E3 = Table.ExpandRecordColumn(E2,"AssignedRec",{"AssignedToName","AssignedToEmail"},{"AssignedToName","AssignedToEmail"}),
    F = Table.TransformColumns(E3,{{"State", each if _=null then null else Text.Proper(Text.Trim(Text.From(_))), type text}}),
    SN = Table.AddColumn(F,"StateNormalized", each if [State]="New" then "Pendiente" else if List.Contains({"Active","In Progress","Resolved"}, [State]) then "En curso" else if List.Contains({"Closed","Done"}, [State]) then "Cerrado" else "Otro"),
    B = Table.AddColumn(SN,"HasOwner", each [AssignedToName]<>null and Text.Trim([AssignedToName])<>"", type logical),
    B1 = Table.AddColumn(B,"IsFeature", each [WorkItemType]="Feature", type logical),
    B2 = Table.AddColumn(B1,"IsUserStory", each [WorkItemType]="User Story", type logical),
    B3 = Table.AddColumn(B2,"IsTask", each [WorkItemType]="Task", type logical),
    B4 = Table.AddColumn(B3,"ProgressWeight", each if [StateNormalized]="Cerrado" then 1 else if [StateNormalized]="En curso" then 0.5 else 0, type number),
    B5 = Table.AddColumn(B4,"SourceMode", each "CSV", type text),
    B6 = Table.AddColumn(B5,"FeatureWorkItemId", each if [IsFeature] then [WorkItemId] else null, Int64.Type),
    B7 = Table.AddColumn(B6,"UserStoryWorkItemId", each null, Int64.Type),
    B8 = Table.AddColumn(B7,"ParentWorkItemId", each null, Int64.Type),
    B9 = Table.AddColumn(B8,"AreaPath", each null, type text),
    B10 = Table.AddColumn(B9,"IterationPath", each null, type text),
    B11 = Table.AddColumn(B10,"CreatedDate", each null, type datetime),
    B12 = Table.AddColumn(B11,"ChangedDate", each null, type datetime),
    B13 = Table.AddColumn(B12,"ClosedDate", each null, type datetime),
    B14 = Table.AddColumn(B13,"Priority", each null, Int64.Type),
    B15 = Table.AddColumn(B14,"BoardColumn", each null, type text),
    B16 = Table.AddColumn(B15,"BoardColumnDone", each null, type logical),
    B17 = Table.AddColumn(B16,"HierarchyLevel", each if [IsFeature] then 1 else if [IsUserStory] then 2 else if [IsTask] then 3 else null, Int64.Type),
    B18 = Table.AddColumn(B17,"HierarchyStatus", each if [TrackCode]=null then "Track no detectado" else "Completa", type text),
    B19 = Table.ReplaceValue(B18,null,"Track sin clasificar",Replacer.ReplaceValue,{"TrackName"}),
    B20 = Table.ReplaceValue(B19,null,"T00",Replacer.ReplaceValue,{"TrackCode"}),
    S = Table.SelectColumns(B20,{"WorkItemId","WorkItemType","TrackCode","TrackName","FeatureWorkItemId","FeatureTitle","UserStoryWorkItemId","UserStoryTitle","TaskTitle","DisplayTitle","AssignedToName","AssignedToEmail","State","StateNormalized","Tags","HasOwner","IsFeature","IsUserStory","IsTask","SortOrder","ProgressWeight","SourceMode","ParentWorkItemId","AreaPath","IterationPath","CreatedDate","ChangedDate","ClosedDate","Priority","BoardColumn","BoardColumnDone","HierarchyLevel","HierarchyStatus"})
in
    S
