let
    Raw = OData.Feed(pODataUrl, null, [Implementation="2.0"]),
    T0 = FunctionsAzureDevOps[FnCoalesceColumn](Raw,{"WorkItemId","ID","Id"},"WorkItemId"),
    T1 = FunctionsAzureDevOps[FnCoalesceColumn](T0,{"WorkItemType","Work Item Type"},"WorkItemType"),
    T2 = FunctionsAzureDevOps[FnCoalesceColumn](T1,{"Title"},"Title"),
    T3 = FunctionsAzureDevOps[FnCoalesceColumn](T2,{"AssignedTo"},"Assigned To"),
    T4 = FunctionsAzureDevOps[FnCoalesceColumn](T3,{"State"},"State"),
    T5 = FunctionsAzureDevOps[FnCoalesceColumn](T4,{"Tags"},"Tags"),
    I = Table.AddIndexColumn(T5,"SortOrder",1,1,Int64.Type),
    A = Table.AddColumn(I,"AssignedRec", each FunctionsAzureDevOps[FnParseAssignedTo](try Text.From([Assigned To]) otherwise null)),
    E = Table.ExpandRecordColumn(A,"AssignedRec",{"AssignedToName","AssignedToEmail"},{"AssignedToName","AssignedToEmail"}),
    N = Table.AddColumn(E,"TrackRec", each FunctionsAzureDevOps[FnTrackFromText]([Title])),
    X = Table.ExpandRecordColumn(N,"TrackRec",{"TrackCode","TrackName"},{"TrackCode","TrackName"}),
    W = Table.AddColumn(X,"WorkItemTypeN", each Text.Proper(Text.Trim(Text.From([WorkItemType])))),
    R = Table.RenameColumns(W,{{"WorkItemTypeN","WorkItemType"}},MissingField.Ignore),
    S0 = Table.AddColumn(R,"FeatureTitle", each if [WorkItemType]="Feature" then [Title] else null),
    S1 = Table.AddColumn(S0,"UserStoryTitle", each if [WorkItemType]="User Story" then [Title] else null),
    S2 = Table.AddColumn(S1,"TaskTitle", each if [WorkItemType]="Task" then [Title] else null),
    S3 = Table.AddColumn(S2,"DisplayTitle", each [Title]),
    S4 = Table.AddColumn(S3,"StateNormalized", each if [State]="New" then "Pendiente" else if List.Contains({"Active","In Progress","Resolved"}, [State]) then "En curso" else if List.Contains({"Closed","Done"}, [State]) then "Cerrado" else "Otro"),
    S5 = Table.AddColumn(S4,"HasOwner", each [AssignedToName]<>null and Text.Trim([AssignedToName])<>"", type logical),
    S6 = Table.AddColumn(S5,"IsFeature", each [WorkItemType]="Feature", type logical),
    S7 = Table.AddColumn(S6,"IsUserStory", each [WorkItemType]="User Story", type logical),
    S8 = Table.AddColumn(S7,"IsTask", each [WorkItemType]="Task", type logical),
    S9 = Table.AddColumn(S8,"ProgressWeight", each if [StateNormalized]="Cerrado" then 1 else if [StateNormalized]="En curso" then 0.5 else 0, type number),
    S10 = Table.AddColumn(S9,"SourceMode", each "OData", type text),
    ECols = FunctionsAzureDevOps[FnEnsureColumns](S10,{"FeatureWorkItemId","UserStoryWorkItemId","ParentWorkItemId","AreaPath","IterationPath","CreatedDate","ChangedDate","ClosedDate","Priority","BoardColumn","BoardColumnDone","HierarchyLevel","HierarchyStatus"}),
    S = Table.SelectColumns(ECols,{"WorkItemId","WorkItemType","TrackCode","TrackName","FeatureWorkItemId","FeatureTitle","UserStoryWorkItemId","UserStoryTitle","TaskTitle","DisplayTitle","AssignedToName","AssignedToEmail","State","StateNormalized","Tags","HasOwner","IsFeature","IsUserStory","IsTask","SortOrder","ProgressWeight","SourceMode","ParentWorkItemId","AreaPath","IterationPath","CreatedDate","ChangedDate","ClosedDate","Priority","BoardColumn","BoardColumnDone","HierarchyLevel","HierarchyStatus"})
in
    S
